version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      microsoft:
        patterns:
          - "github.com/Azure/*"
          - "github.com/microsoft/*"
          - "github.com/microsoftgraph/*"
      go-stdx:
        patterns:
          - "golang.org/x/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
